//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;103&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;函館本線[札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot; : &quot;いしかりライナー（江別～札幌間快速）&quot;,&quot;time&quot; : &quot;12:07&quot;,&quot;to&quot; : &quot;ほしみ&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(岩見沢駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot; : &quot;いしかりライナー（札幌～手稲間快速）&quot;,&quot;time&quot; : &quot;12:35&quot;,&quot;to&quot; : &quot;小樽&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;特急&quot;,&quot;name&quot; : &quot;ライラック２２号&quot;,&quot;time&quot; : &quot;13:00&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 0,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(深川-近文間)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;区快&... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;220&quot; : {&quot;departures_datetime&quot; : &quot;201906261205&quot;,&quot;departures&quot; : {&quot;石勝線[南千歳・札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;特急&quot;,&quot;name&quot; : &quot;スーパーとかち６号&quot;,&quot;time&quot; : &quot;13:12&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 0,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(トマム-新得間)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;13:42&quot;,&quot;to&quot; : &quot;千歳&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;特急&quot;,&quot;name&quot; : &quot;スーパーとかち８号&quot;,&quot;time&quot; : &quot;15:32&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &q... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;215&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;千歳線[札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:14&quot;,&quot;to&quot; : &quot;小樽&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;特急&quot;,&quot;name&quot; : &quot;スーパー北斗７号&quot;,&quot;time&quot; : &quot;12:59&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 0,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(長和-有珠間)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;13:21&quot;,&quot;to&quot; : &quot;小樽&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;特急&quot;,&quot;name&quot; : &quot;スーパー北斗９号&... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _215 {
            get {
                return ResourceManager.GetString("_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;244&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;千歳線[札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;快速&quot;,&quot;name&quot; : &quot;エアポート１２１号&quot;,&quot;time&quot; : &quot;12:07&quot;,&quot;to&quot; : &quot;小樽&quot;,&quot;status&quot; : 0,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(南千歳駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:13&quot;,&quot;to&quot; : &quot;手稲&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(千歳駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;快速&quot;,&quot;name&quot; : &quot;エアポート１２３号&quot;,&quot;time&quot; : &quot;12:22&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(新千歳空港駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;快速&quot;,&quot;name&quot... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _244 {
            get {
                return ResourceManager.GetString("_244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;245&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;千歳線[（普通・快速）札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;快速&quot;,&quot;name&quot; : &quot;エアポート１２１号&quot;,&quot;time&quot; : &quot;12:03&quot;,&quot;to&quot; : &quot;小樽&quot;,&quot;status&quot; : 0,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(南千歳駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;快速&quot;,&quot;name&quot; : &quot;エアポート１２３号&quot;,&quot;time&quot; : &quot;12:18&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(新千歳空港駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;快速&quot;,&quot;name&quot; : &quot;エアポート１２５号&quot;,&quot;time&quot; : &quot;12:33&quot;,&quot;to&quot; : &quot;小樽&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _245 {
            get {
                return ResourceManager.GetString("_245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;259&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;学園都市線[札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:04&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(あいの里公園駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:22&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(北海道医療大学駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:44&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _259 {
            get {
                return ResourceManager.GetString("_259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;261&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;学園都市線[札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:11&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(北海道医療大学駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:49&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;13:38&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&q... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _261 {
            get {
                return ResourceManager.GetString("_261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;262&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;学園都市線[札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:06&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(北海道医療大学駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:45&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;13:30&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&q... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _262 {
            get {
                return ResourceManager.GetString("_262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;118&quot; : {&quot;departures_datetime&quot; : &quot;201906261205&quot;,&quot;departures&quot; : {&quot;函館本線[深川・札幌・新千歳空港方面へ]@1&quot; : [{&quot;class&quot; : &quot;特急&quot;,&quot;name&quot; : &quot;ライラック２４号&quot;,&quot;time&quot; : &quot;13:00&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;13:47&quot;,&quot;to&quot; : &quot;滝川&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;特急&quot;,&quot;name&quot; : &quot;ライラック２６号&quot;,&quot;time&quot; : &quot;14:00&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;特急&quot;,&quot;name&quot; : &quot;カ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;002&quot; : {&quot;departures_datetime&quot; : &quot;201906261205&quot;,&quot;departures&quot; : {&quot;津軽海峡線[青森・新青森方面へ]@1&quot; : [{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;はやぶさ２４号&quot;,&quot;time&quot; : &quot;13:35&quot;,&quot;to&quot; : &quot;東京&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;はやぶさ３０号&quot;,&quot;time&quot; : &quot;15:35&quot;,&quot;to&quot; : &quot;東京&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;}],&quot;津軽海峡線[函館方面へ]@1&quot; : []},&quot;arrivals_datetime&quot; : &quot;201906261205&quot;,&quot;arrivals&quot; : {&quot;津軽海峡線[青森・新青森方面から]@1&quot; : [{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;はやぶさ１５号&quot;,&quot;time&quot; : &quot;13:46&quot;,&quot;to&quot; : &quot;新函館北斗&quot;,&quot;status&quot; : 7 [残りの文字列は... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;076&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;函館本線[札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot; : &quot;いしかりライナー（手稲～札幌間快速）&quot;,&quot;time&quot; : &quot;12:10&quot;,&quot;to&quot; : &quot;岩見沢&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(小樽駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:20&quot;,&quot;to&quot; : &quot;千歳&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;快速&quot;,&quot;name&quot; : &quot;エアポート１３０号&quot;,&quot;time&quot; : &quot;12:30&quot;,&quot;to&quot; : &quot;新千歳空港&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _76 {
            get {
                return ResourceManager.GetString("_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;082&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;函館本線[札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:12&quot;,&quot;to&quot; : &quot;千歳&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(銭函駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot; : &quot;いしかりライナー（手稲～札幌間快速）&quot;,&quot;time&quot; : &quot;12:31&quot;,&quot;to&quot; : &quot;岩見沢&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(小樽駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:41&quot;,&quot;to&quot; : &quot;千歳&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot; : &... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _82 {
            get {
                return ResourceManager.GetString("_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;085&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;函館本線[札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot; : &quot;いしかりライナー（手稲～札幌間快速）&quot;,&quot;time&quot; : &quot;12:09&quot;,&quot;to&quot; : &quot;札幌&quot;,&quot;status&quot; : 0,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(銭函-星置間)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot; : &quot;いしかりライナー（札幌～江別間快速）&quot;,&quot;time&quot; : &quot;12:11&quot;,&quot;to&quot; : &quot;岩見沢&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;快速&quot;,&quot;name&quot; : &quot;エアポート１２４号&quot;,&quot;time&quot; : &quot;12:22&quot;,&quot;to&quot; : &quot;新千歳空港&quot;,&quot;status&quot; : 0,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(小樽-小樽築港間)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _85 {
            get {
                return ResourceManager.GetString("_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;091&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;函館本線[小樽方面へ]@1&quot; : [{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot; : &quot;いしかりライナー（江別～札幌間快速）&quot;,&quot;time&quot; : &quot;12:06&quot;,&quot;to&quot; : &quot;ほしみ&quot;,&quot;status&quot; : 0,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(札幌-苗穂間)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;快速&quot;,&quot;name&quot; : &quot;エアポート１１５号&quot;,&quot;time&quot; : &quot;12:13&quot;,&quot;to&quot; : &quot;小樽&quot;,&quot;status&quot; : 0,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(苗穂-白石間)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:18&quot;,&quot;to&quot; : &quot;手稲&quot;,&quot;status&quot; : 0,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(白石駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;区快&quot;,&q... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _91 {
            get {
                return ResourceManager.GetString("_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;services&quot; : {&quot;099&quot; : {&quot;departures_datetime&quot; : &quot;201906261203&quot;,&quot;departures&quot; : {&quot;函館本線[札幌方面へ]@1&quot; : [{&quot;class&quot; : &quot;普通&quot;,&quot;name&quot; : &quot;普通&quot;,&quot;time&quot; : &quot;12:15&quot;,&quot;to&quot; : &quot;手稲&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(江別駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot; : &quot;いしかりライナー（江別～札幌間快速）&quot;,&quot;time&quot; : &quot;12:25&quot;,&quot;to&quot; : &quot;ほしみ&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;(岩見沢駅)&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;区快&quot;,&quot;name&quot; : &quot;いしかりライナー（札幌～手稲間快速）&quot;,&quot;time&quot; : &quot;12:30&quot;,&quot;to&quot; : &quot;小樽&quot;,&quot;status&quot; : 5,&quot;add&quot;  : &quot;&quot;, &quot;now&quot; : &quot;&quot;, &quot;dest&quot; : &quot;&quot;},{&quot;class&quot; : &quot;区快&quot;,&qu... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _99 {
            get {
                return ResourceManager.GetString("_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;Chitose_Tomakomai&quot;:[91,92,93,234,235,236,238,239,240,241,242,243,244,245,248,215],&quot;Hakodate_Iwamizawa&quot;:[91,92,93,94,95,96,97,98,99,100,101,102,103],&quot;Hakodate_Otaru&quot;:[91,90,89,88,87,86,85,84,83,82,81,79,78,77,76],&quot;Nemuro_Furano&quot;:[306,307,308,309,310,311,312,500,314,315,316,317,318,319,320,325],&quot;Nemuro_Obihiro&quot;:[325,326,329,331,332,333,334,335,336,338,339,340,342,343,344,345,348,351,352,353,354,355,357,358,359,360],&quot;Sassyo&quot;:[91,90,251,252,253,254,255,256,257,258,259,260,261,262],&quot;Sekisyo&quot;:[244,245,220,284,2 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LineDataDic {
            get {
                return ResourceManager.GetString("LineDataDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,{&quot;ID&quot;:76,&quot;value&quot;:&quot;小樽&quot;,&quot;hira&quot;:&quot;おたる&quot;,&quot;kata&quot;:&quot;オタル&quot;,&quot;en&quot;:&quot;Otaru&quot;,&quot;stationArea&quot;:0,&quot;Position&quot;:{&quot;Hakodate_Otaru&quot;:15},&quot;IsEndStation&quot;:true}, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stationArray {
            get {
                return ResourceManager.GetString("stationArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;おたる&quot;:76,&quot;みなみおたる&quot;:77,&quot;おたるちっこう&quot;:78,&quot;あさり&quot;:79,&quot;ぜにばこ&quot;:81,&quot;ほしみ&quot;:82,&quot;ほしおき&quot;:83,&quot;いなほ&quot;:84,&quot;ていね&quot;:85,&quot;いなづみこうえん&quot;:86,&quot;はっさむ&quot;:87,&quot;はっさむちゅうおう&quot;:88,&quot;ことに&quot;:89,&quot;そうえん&quot;:90,&quot;さっぽろ&quot;:91,&quot;なえぼ&quot;:92,&quot;しろいし&quot;:93,&quot;あつべつ&quot;:94,&quot;しんりんこうえん&quot;:95,&quot;おおあさ&quot;:96,&quot;のっぽろ&quot;:97,&quot;たかさご&quot;:98,&quot;えべつ&quot;:99,&quot;とよほろ&quot;:100,&quot;ほろむい&quot;:101,&quot;かみほろむい&quot;:102,&quot;いわみざわ&quot;:103,&quot;とまこまい&quot;:215,&quot;おいわけ&quot;:220,&quot;へいわ&quot;:234,&quot;しんさっぽろ&quot;:235,&quot;かみのっぽろ&quot;:236,&quot;きたひろしま&quot;:238,&quot;しままつ&quot;:239,&quot;めぐみの&quot;:240,&quot;えにわ&quot;:241,&quot;さっぽろびーるていえん&quot;:242,&quot;おさつ&quot;:243,&quot;ちとせ&quot;:244,&quot;みなみちとせ&quot;:245,&quot;うえなえ&quot;:248,&quot;はちけん&quot;:251,&quot;しんかわ&quot;:252,&quot;しんことに&quot;:253,&quot;たいへい&quot;:254,&quot;ゆりがはら&quot;:255,&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StationHiraDic {
            get {
                return ResourceManager.GetString("StationHiraDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;オタル&quot;:76,&quot;ミナミオタル&quot;:77,&quot;オタルチッコウ&quot;:78,&quot;アサリ&quot;:79,&quot;ゼニバコ&quot;:81,&quot;ホシミ&quot;:82,&quot;ホシオキ&quot;:83,&quot;イナホ&quot;:84,&quot;テイネ&quot;:85,&quot;イナヅミコウエン&quot;:86,&quot;ハッサム&quot;:87,&quot;ハッサムチュウオウ&quot;:88,&quot;コトニ&quot;:89,&quot;ソウエン&quot;:90,&quot;サッポロ&quot;:91,&quot;ナエボ&quot;:92,&quot;シロイシ&quot;:93,&quot;アツベツ&quot;:94,&quot;シンリンコウエン&quot;:95,&quot;オオアサ&quot;:96,&quot;ノッポロ&quot;:97,&quot;タカサゴ&quot;:98,&quot;エベツ&quot;:99,&quot;トヨホロ&quot;:100,&quot;ホロムイ&quot;:101,&quot;カミホロムイ&quot;:102,&quot;イワミザワ&quot;:103,&quot;トマコマイ&quot;:215,&quot;オイワケ&quot;:220,&quot;ヘイワ&quot;:234,&quot;シンサッポロ&quot;:235,&quot;カミノッポロ&quot;:236,&quot;キタヒロシマ&quot;:238,&quot;シママツ&quot;:239,&quot;メグミノ&quot;:240,&quot;エニワ&quot;:241,&quot;サッポロビールテイエン&quot;:242,&quot;オサツ&quot;:243,&quot;チトセ&quot;:244,&quot;ミナミチトセ&quot;:245,&quot;ウエナエ&quot;:248,&quot;ハチケン&quot;:251,&quot;シンカワ&quot;:252,&quot;シンコトニ&quot;:253,&quot;タイヘイ&quot;:254,&quot;ユリガハラ&quot;:255,&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StationKanaDic {
            get {
                return ResourceManager.GetString("StationKanaDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;小樽&quot;:76,&quot;南小樽&quot;:77,&quot;小樽築港&quot;:78,&quot;朝里&quot;:79,&quot;銭函&quot;:81,&quot;ほしみ&quot;:82,&quot;星置&quot;:83,&quot;稲穂&quot;:84,&quot;手稲&quot;:85,&quot;稲積公園&quot;:86,&quot;発寒&quot;:87,&quot;発寒中央&quot;:88,&quot;琴似&quot;:89,&quot;桑園&quot;:90,&quot;札幌&quot;:91,&quot;苗穂&quot;:92,&quot;白石&quot;:93,&quot;厚別&quot;:94,&quot;森林公園&quot;:95,&quot;大麻&quot;:96,&quot;野幌&quot;:97,&quot;高砂&quot;:98,&quot;江別&quot;:99,&quot;豊幌&quot;:100,&quot;幌向&quot;:101,&quot;上幌向&quot;:102,&quot;岩見沢&quot;:103,&quot;苫小牧&quot;:215,&quot;追分&quot;:220,&quot;平和&quot;:234,&quot;新札幌&quot;:235,&quot;上野幌&quot;:236,&quot;北広島&quot;:238,&quot;島松&quot;:239,&quot;恵み野&quot;:240,&quot;恵庭&quot;:241,&quot;サッポロビール庭園&quot;:242,&quot;長都&quot;:243,&quot;千歳&quot;:244,&quot;南千歳&quot;:245,&quot;植苗&quot;:248,&quot;八軒&quot;:251,&quot;新川&quot;:252,&quot;新琴似&quot;:253,&quot;太平&quot;:254,&quot;百合が原&quot;:255,&quot;篠路&quot;:256,&quot;拓北&quot;:257,&quot;あいの里教育大&quot;:258,&quot;あいの里公園&quot;:259,&quot;石狩太美&quot;:260,&quot;石狩当別&quot;:261,&quot;北海道医療大学&... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StationNameDic {
            get {
                return ResourceManager.GetString("StationNameDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;Otaru&quot;:76,&quot;Minami-Otaru&quot;:77,&quot;Otaruchikko&quot;:78,&quot;Asari&quot;:79,&quot;Zenibako&quot;:81,&quot;Hoshimi&quot;:82,&quot;Hoshioki&quot;:83,&quot;Inaho&quot;:84,&quot;Teine&quot;:85,&quot;Inazumikoen&quot;:86,&quot;Hassamu&quot;:87,&quot;Hassamuchuo&quot;:88,&quot;Kotoni&quot;:89,&quot;Soen&quot;:90,&quot;Sapporo&quot;:91,&quot;Naebo&quot;:92,&quot;Shiroishi&quot;:93,&quot;Atsubetsu&quot;:94,&quot;Shinrinkoen&quot;:95,&quot;Oasa&quot;:96,&quot;Nopporo&quot;:97,&quot;Takasago&quot;:98,&quot;Ebetsu&quot;:99,&quot;Toyohoro&quot;:100,&quot;Horomui&quot;:101,&quot;Kami-Horomui&quot;:102,&quot;Iwamizawa&quot;:103,&quot;Tomakomai&quot;:215,&quot;Oiwake&quot;:220,&quot;Heiwa&quot;:234,&quot;Shin-Sapporo&quot;:235,&quot;Kami-Nopporo&quot;:236,&quot;Kita-Hiroshima&quot;:238,&quot;Shimamatsu&quot;:239,&quot;Megumino&quot;:240,&quot;Eniwa [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StationRomanDic {
            get {
                return ResourceManager.GetString("StationRomanDic", resourceCulture);
            }
        }
    }
}
